# Numpy

Numerisk Python
- Arrays (fält)
- Lik listor
- Matematiska operationer på arrays
- Modellera vektorer och matriser

In [10]:
import numpy as np

#pip install numpy - om man har vanlig python

array1 = np.array([1,2,3,4])
lista1 = [1,2,3,4]

print(f"Array: {array1}")
print(f"Lista: {lista}")

#indexera arrays, fungerar på samma sätt som att indexera listor "[]"
print(array1[2])

#multiplicera alla tal med 2
array2 = array1*2
print(array2)

lista2 = lista1*2
print(lista2)

kvadrater = array1**2
print(kvadrater)

Array: [1 2 3 4]
Lista: [1, 2, 3, 4]
3
[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]
[ 1  4  9 16]


## Användbara numpy-funktioner
- zeros
- ones
- arange
- linspace
- matematiska funktioner och konstanter: pi, sqrt

In [14]:
import numpy as np

#arange
tal = np.arange(10)
print(tal)

#sqrt
print(np.sqrt(tal))

nollor = np.zeros(6)
print(nollor)

ettor = np.ones(6)
print(ettor)

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


### Simulera tärningskast

In [18]:
import numpy as np
import random as rnd

#array med nollor för att preallokera minne
utfall = np.zeros(6, dtype=int)

antal_kast = 100000
for i in range(antal_kast):
    kast = rnd.randint(1,6)
    utfall[kast-1] += 1

print(f"Tärningskast: {utfall}")
print(f"Sannolikhet: {utfall/antal_kast}")

Tärningskast: [16683 16826 16515 16688 16552 16736]
Sannolikhet: [0.16683 0.16826 0.16515 0.16688 0.16552 0.16736]
